spring:
  application:
    name: shinhan_cubeon_task
  devtools:
    restart:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/Review
    username: root
    password: qpalzm0915
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 60
      max-lifetime: 300000
  cache:
    type: redis
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        generate_statistics: false
        use_sql_comments: false
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        type:
          descriptor:
            sql: false
    generate-ddl: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  lifecycle:
    timeout-per-shutdown-phase: 10s
  sql:
    init:
      mode: always

springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1
  enable-native-support: true

server:
  port: 7200
  compression:
    enabled: true
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  error:
    include-exception: true
    include-stacktrace: always
